class NeuralWeightOptimizationMetrics:
    def __init__(self, algorithm_name: str = "Nadam",
                 initial_loss: float = 0.0,
                 final_loss: float = 0.0,
                 convergence_iterations: int = 0,
                 adamw_weight_decay_efficiency: float = 0.0,
                 radam_rectification_stability: float = 0.0,
                 lookahead_convergence_speed: float = 0.0,
                 nadam_nesterov_acceleration: float = 0.0,
                 nadam_efficiency: float = 0.0,
                 nadam_stability: float = 0.0,
                 nadam_trend: str = "stable",
                 lamb_layer_wise_adaptation: float = 0.0,
                 adabelief_belief_correction: float = 0.0,
                 lion_momentum_efficiency: float = 0.0,
                 sam_sharpness_awareness: float = 0.0,
                 swats_switching_efficiency: float = 0.0,
                 neural_weight_integration_score: float = 0.0,
                 overall_score: float = 0.0,
                 optimization_time: float = 0.0,
                 timestamp: str = ""):
        self.algorithm_name = algorithm_name
        self.initial_loss = initial_loss
        self.final_loss = final_loss
        self.convergence_iterations = convergence_iterations
        self.adamw_weight_decay_efficiency = adamw_weight_decay_efficiency
        self.radam_rectification_stability = radam_rectification_stability
        self.lookahead_convergence_speed = lookahead_convergence_speed
        self.nadam_nesterov_acceleration = nadam_nesterov_acceleration
        self.nadam_efficiency = nadam_efficiency
        self.nadam_stability = nadam_stability
        self.nadam_trend = nadam_trend
        self.lamb_layer_wise_adaptation = lamb_layer_wise_adaptation
        self.adabelief_belief_correction = adabelief_belief_correction
        self.lion_momentum_efficiency = lion_momentum_efficiency
        self.sam_sharpness_awareness = sam_sharpness_awareness
        self.swats_switching_efficiency = swats_switching_efficiency
        self.neural_weight_integration_score = neural_weight_integration_score
        self.overall_score = overall_score
        self.optimization_time = optimization_time
        self.timestamp = timestamp


