import re
import threading
from typing import List
from LC.Constructor.LUCIA_20260923_031455.celebro.CMFG.SBSTM.RPLC_ReformuladorLinguisticoLucia_ReformuladorLinguisticoLucia import ReformuladorLinguisticoLucia  # CLASSPACK
